[font]
size = 15

[font.normal]
family = "SauceCodePro Nerd Font"
# family = "SauceCodeProNerdFont"
style = "Regular"


[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
startup_mode = "Maximized"
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "Buttonless"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/everforest.toml"

   # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
