[font]
size = 12
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
italic = { family = "FiraMono Nerd Font Mono", style = "Italic" }

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.98

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[terminal.shell]
program = "/opt/homebrew/bin/tmux" 
args = ["new-session", "-A", "-D", "-s", "home"]
#
#
[general]
import = [
  "~/.config/alacritty/everforest.toml"
]
